const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const csrf=window.CCO.csrf; let hoursChart=null,currentMemberId=null,securityState={};
const fmtMinutes=(m=0)=>{m=Number(m||0);return `${Math.floor(m/60)}h ${m%60}m`};
const esc=(v='')=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const badge=s=>`<span class="status-badge status-${esc(s)}">${esc(s)}</span>`;
function toast(msg,type='ok'){const el=document.createElement('div');el.className=`toast ${type}`;el.textContent=msg;$('#toastHost').appendChild(el);setTimeout(()=>el.remove(),4200)}
async function api(url,opt={}){opt.headers={...(opt.headers||{}),'X-CSRF-Token':csrf};if(opt.body&&typeof opt.body!=='string'){opt.headers['Content-Type']='application/json';opt.body=JSON.stringify(opt.body)}const r=await fetch(url,opt);let d;try{d=await r.json()}catch{d={ok:false,error:await r.text()}}if(!r.ok||d?.ok===false)throw new Error(d?.error||`HTTP ${r.status}`);return d}
function openModal(id){$('#'+id)?.classList.add('open')} function closeModal(id){$('#'+id)?.classList.remove('open')} window.closeModal=closeModal;
function criticalConfirm(title,text,fn){$('#criticalTitle').textContent=title;$('#criticalText').textContent=text;$('#criticalInput').value='';$('#criticalAccept').onclick=async()=>{if($('#criticalInput').value.trim().toUpperCase()!=='CONFIRM'){return toast('Scrie CONFIRM pentru a continua','err')}closeModal('criticalModal');await fn('CONFIRM')};openModal('criticalModal')} window.criticalConfirm=criticalConfirm;

const titles={dashboard:'Dashboard',members:'Membri',timesheets:'Pontaje',operations:'Activitate Operativă',callsigns:'Callsign-uri',tickets:'Ticket-uri',testers:'Testeri',sanctions:'Sancțiuni',inactivity:'Inactivități',resignations:'Demisii',security:'Security Center',backups:'Backups',logs:'Loguri',config:'Configurare',superusers:'Superuser Management'};
const loaders={dashboard:loadOverview,members:loadMembers,timesheets:loadTimesheets,operations:loadOperations,callsigns:loadCallsigns,tickets:loadTickets,testers:loadTesters,sanctions:loadSanctions,inactivity:loadInactivity,resignations:loadResignations,security:loadSecurity,backups:loadBackups,logs:loadLogs,config:loadConfig,superusers:loadSuperusers};
function switchTab(tab){$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));$$('.tab-page').forEach(p=>p.classList.toggle('active',p.id===`tab-${tab}`));if($('#pageTitle'))$('#pageTitle').textContent=titles[tab]||tab;localStorage.setItem('cco-tab',tab);loaders[tab]?.()}
$$('.nav-item').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.tab)));$('#sidebarToggle')?.addEventListener('click',()=>$('#sidebar').classList.toggle('open'));document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#globalSearch')?.focus()}if(e.key==='Escape')$$('.modal.open').forEach(x=>x.classList.remove('open'))});$('#globalSearch')?.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.value.trim()){switchTab('members');$('#memberSearch').value=e.target.value.trim();loadMembers()}});

async function loadOverview(){try{const d=await api('/api/overview');const cards=[['Membri activi',d.stats.members,'PERSONNEL'],['Conducere',d.stats.leadership,'COMMAND'],['Testeri',d.stats.testers,'QA UNIT'],['Ticket-uri',d.stats.tickets,'SUPPORT'],['Pontaje active',d.stats.active_timesheets,'LIVE'],['Ore azi',fmtMinutes(d.stats.minutes_today),'ACTIVITY']];$('#overviewStats').innerHTML=cards.map(x=>`<div class="stat-card"><span>${x[0]}</span><b>${x[1]}</b><small>${x[2]}</small></div>`).join('');$('#recentActivity').innerHTML=d.recent.length?d.recent.map(x=>`<div class="activity-item"><b>${esc(x.type)}</b><small>${esc(x.actor_id||'system')} → ${esc(x.target_id||'-')} · ${esc(x.details||'')}</small></div>`).join(''):'<div class="empty">Fără activitate recentă</div>';if(window.Chart&&$('#hoursChart')){if(hoursChart)hoursChart.destroy();hoursChart=new Chart($('#hoursChart'),{type:'line',data:{labels:d.chart.labels,datasets:[{label:'Ore',data:d.chart.values,tension:.38,fill:true,borderWidth:2}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}}}})}}catch(e){toast(e.message,'err')}}

let memberTimer;['memberSearch','memberStatus','memberRank','memberTester'].forEach(id=>$('#'+id)?.addEventListener(id==='memberSearch'?'input':'change',()=>{clearTimeout(memberTimer);memberTimer=setTimeout(loadMembers,180)}));
async function loadMembers(){try{const p=new URLSearchParams({q:$('#memberSearch')?.value||'',status:$('#memberStatus')?.value||'all',rank:$('#memberRank')?.value||'all',tester:$('#memberTester')?.value||'all'});const rows=await api('/api/members?'+p);$('#membersCount').textContent=`${rows.length} rezultate`;$('#membersTable').innerHTML=rows.length?rows.map(m=>`<tr><td><div class="member-cell"><div class="mini-avatar">${esc((m.first_name||'?')[0])}</div><div><b>${esc(m.first_name||'')} ${esc(m.last_name||'')}</b><div class="muted">${esc(m.discord_id)}</div></div></div></td><td>${esc(m.callsign||'—')}</td><td>${esc(m.rank||'—')}</td><td>${esc(m.internal_id||'—')}</td><td>${m.head_tester?'Șef Tester':m.tester?'Tester':'—'}</td><td>${badge(m.status)}</td><td><button class="btn small ghost" onclick="openMember('${m.discord_id}')">Deschide</button></td></tr>`).join(''):'<tr><td colspan="7" class="empty">Niciun membru</td></tr>'}catch(e){toast(e.message,'err')}}

function operationalRows(rows){return rows.slice(0,80).map(r=>`<tr><td>#${r.id}</td><td>${esc(r.kind)}</td><td>${badge(r.status)}</td><td>${esc(r.created_at)}</td><td>${esc(r.reviewer_id||'—')}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">Fără activitate</td></tr>'}
async function openMember(id,period='week'){try{currentMemberId=id;const d=await api(`/api/member/${id}?period=${period}`),m=d.member;$('#memberProfile').innerHTML=`
<div class="profile-header"><div class="profile-avatar">${esc((m.first_name||'?')[0])}</div><div><span class="section-kicker">MEMBER PROFILE</span><h2>${esc(m.first_name||'')} ${esc(m.last_name||'')}</h2><p>${esc(m.callsign||'Fără callsign')} · ${esc(m.rank||'Fără grad')} · ID ${esc(m.internal_id||'—')}</p></div><div class="profile-status">${badge(m.status)}</div></div>
<div class="profile-grid"><div class="profile-stat"><span>PONTAJ TOTAL</span><b>${fmtMinutes(d.stats.total_minutes)}</b></div><div class="profile-stat"><span>PERIOADĂ</span><b>${fmtMinutes(d.stats.period_minutes)}</b></div><div class="profile-stat"><span>BULETINE</span><b>${d.stats.buletine}</b></div><div class="profile-stat"><span>FILAJE</span><b>${d.stats.filaje}</b></div><div class="profile-stat"><span>INTEROGATORII</span><b>${d.stats.interogatorii}</b></div><div class="profile-stat"><span>ACȚIUNI</span><b>${d.stats.actiuni}</b></div></div>
<div class="criteria-note"><b>Activitate pentru promovare</b><span>Buletine: ${d.stats.buletine}</span><span>Filaje: ${d.stats.filaje}</span><span>Interogatorii: ${d.stats.interogatorii}</span><span>Acțiuni: ${d.stats.actiuni}</span><small>Valorile sunt informative. Promovarea nu este blocată automat.</small></div>
<div class="toolbar-card"><select onchange="openMember('${id}',this.value)"><option value="today">Azi</option><option value="week" ${period==='week'?'selected':''}>7 zile</option><option value="month" ${period==='month'?'selected':''}>Luna</option><option value="all" ${period==='all'?'selected':''}>Total</option></select></div>
<div class="profile-actions"><button class="btn success small" onclick="memberAction('promote')">Promovează</button><button class="btn ghost small" onclick="memberAction('demote')">Retrogradează</button><button class="btn ghost small" onclick="setRankPrompt()">Schimbă grad</button><button class="btn ghost small" onclick="editIdentityPrompt('${esc(m.first_name||'')}','${esc(m.last_name||'')}','${esc(m.internal_id||'')}')">Edit date</button><button class="btn ghost small" onclick="callsignAssignPrompt('${id}')">Callsign</button><button class="btn ghost small" onclick="memberAction('${m.tester?'remove_tester':'add_tester'}')">${m.tester?'Scoate Tester':'Adaugă Tester'}</button>${m.status==='suspended'?'<button class="btn success small" onclick="memberAction(\'reactivate\')">Reactivează</button>':'<button class="btn ghost small" onclick="suspendPrompt()">Suspendă</button>'}<button class="btn danger small" onclick="removePrompt()">Elimină</button></div>
<div class="profile-tabs"><button class="active" onclick="showProfilePane('times',this)">Pontaje</button><button onclick="showProfilePane('ops',this)">Activitate</button><button onclick="showProfilePane('sanctions',this)">Sancțiuni</button><button onclick="showProfilePane('history',this)">Istoric</button></div>
<div class="profile-subpane" data-profile-pane="times"><div class="table-wrap"><table><thead><tr><th>Clock In</th><th>Clock Out</th><th>Durată</th><th>Status</th><th>Anulat de</th></tr></thead><tbody>${d.timesheets.slice(0,100).map(t=>`<tr><td>${esc(t.clock_in)}</td><td>${esc(t.clock_out||'—')}</td><td>${fmtMinutes(t.duration_minutes)}</td><td>${badge(t.status)}</td><td>${esc(t.cancelled_by||'—')}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">Fără pontaje</td></tr>'}</tbody></table></div></div>
<div class="profile-subpane" data-profile-pane="ops" style="display:none"><div class="table-wrap"><table><thead><tr><th>#</th><th>Tip</th><th>Status</th><th>Creat</th><th>Reviewer</th></tr></thead><tbody>${operationalRows(d.operations)}</tbody></table></div></div>
<div class="profile-subpane" data-profile-pane="sanctions" style="display:none"><div class="logs-feed">${d.sanctions.map(s=>`<div class="log-item"><b>${s.requested_type==='AV'&&s.type==='FW'?'AV → ':''}${esc(s.type)} ${s.stage}/${s.total_stages}</b><small>${esc(s.reason)} · ${esc(s.status)} · expiră ${esc(s.expires_at||'—')}</small></div>`).join('')||'<div class="empty">Fără sancțiuni</div>'}</div></div>
<div class="profile-subpane" data-profile-pane="history" style="display:none"><div class="logs-feed">${d.history.map(h=>`<div class="log-item"><b>${esc(h.type)}</b><small>${esc(h.details||'')} · ${esc(h.created_at)}</small></div>`).join('')||'<div class="empty">Fără istoric</div>'}</div></div>`;openModal('memberModal')}catch(e){toast(e.message,'err')}} window.openMember=openMember;
function showProfilePane(name,btn){$$('[data-profile-pane]').forEach(x=>x.style.display=x.dataset.profilePane===name?'block':'none');btn.parentElement.querySelectorAll('button').forEach(x=>x.classList.remove('active'));btn.classList.add('active')} window.showProfilePane=showProfilePane;

async function memberAction(action,extra={}){if(!currentMemberId)return;try{const d=await api(`/api/member/${currentMemberId}/action`,{method:'POST',body:{action,...extra}});toast('Acțiune efectuată');openMember(currentMemberId)}catch(e){if(e.message.startsWith('SELECT_CALLSIGN:')){const opts=e.message.substring('SELECT_CALLSIGN:'.length).split('|');const cs=prompt(`Alege unul dintre callsign-urile libere:\n${opts.join('\n')}`,opts[0]);if(cs&&opts.includes(cs.trim().toUpperCase()))return memberAction(action,{...extra,callsign:cs.trim().toUpperCase()})}toast(e.message,'err')}} window.memberAction=memberAction;
function setRankPrompt(){const rank=prompt('Scrie exact gradul nou:');if(rank)memberAction('set_rank',{rank})} window.setRankPrompt=setRankPrompt;
function editIdentityPrompt(first,last,id){const f=prompt('Nume:',first);if(f===null)return;const l=prompt('Prenume:',last);if(l===null)return;const i=prompt('ID:',id);if(i===null)return;memberAction('edit_identity',{first_name:f,last_name:l,internal_id:i})} window.editIdentityPrompt=editIdentityPrompt;
function suspendPrompt(){const r=prompt('Motiv suspendare:');if(r)memberAction('suspend',{reason:r})} window.suspendPrompt=suspendPrompt;
function removePrompt(){const r=prompt('Motiv eliminare:');if(r)criticalConfirm('Eliminare membru','Membrul va primi OUT/remove și kick. Acțiunea rămâne în audit.',confirm=>memberAction('remove',{reason:r,confirm}))} window.removePrompt=removePrompt;
function callsignAssignPrompt(id){const cs=prompt('Callsign nou:');if(cs)assignCallsign(id,cs)} window.callsignAssignPrompt=callsignAssignPrompt;

async function openAddMember(){openModal('addMemberModal');await refreshNewMemberCallsigns()} window.openAddMember=openAddMember;
async function refreshNewMemberCallsigns(){try{const rank=$('#newMemberRank').value,d=await api('/api/callsigns/available?rank='+encodeURIComponent(rank));$('#newMemberCallsign').innerHTML=d.callsigns.length?d.callsigns.map((x,i)=>`<option value="${esc(x)}">${esc(x)}${!d.leadership&&i===0?' — automat':''}</option>`).join(''):'<option value="">NU EXISTĂ CALLSIGN LIBER</option>'}catch(e){toast(e.message,'err')}} window.refreshNewMemberCallsigns=refreshNewMemberCallsigns;
async function saveNewMember(){const body={user_id:$('#newMemberUser').value.trim(),first_name:$('#newMemberFirst').value.trim(),last_name:$('#newMemberLast').value.trim(),internal_id:$('#newMemberInternal').value.trim(),rank:$('#newMemberRank').value,callsign:$('#newMemberCallsign').value};try{await api('/api/members/add',{method:'POST',body});toast('Membru adăugat');closeModal('addMemberModal');loadMembers()}catch(e){toast(e.message,'err')}} window.saveNewMember=saveNewMember;

async function loadTimesheets(){try{const p=new URLSearchParams({period:$('#timePeriod')?.value||'week',status:$('#timeStatus')?.value||'all',user_id:$('#timeUser')?.value||''}),d=await api('/api/timesheets?'+p);$('#timeTotal').textContent=fmtMinutes(d.total_minutes);$('#timeCount').textContent=d.rows.length;$('#timesheetsTable').innerHTML=d.rows.map(t=>`<tr><td>${esc(t.callsign||'—')} ${esc(t.first_name||'')} ${esc(t.last_name||'')}</td><td>${esc(t.rank||'—')}</td><td>${esc(t.clock_in)}</td><td>${esc(t.clock_out||'—')}</td><td>${fmtMinutes(t.duration_minutes)}</td><td>${badge(t.status)}</td><td>${esc(t.cancelled_by||'—')}</td></tr>`).join('')||'<tr><td colspan="7" class="empty">Fără pontaje</td></tr>'}catch(e){toast(e.message,'err')}} window.loadTimesheets=loadTimesheets;

async function loadOperations(){try{const p=new URLSearchParams({kind:$('#opKind')?.value||'all',status:$('#opStatus')?.value||'all',user_id:$('#opUser')?.value||''});const [rows,reqs]=await Promise.all([api('/api/operations?'+p),api('/api/action-requests')]);$('#operationsTable').innerHTML=rows.map(r=>`<tr><td><input class="op-check" type="checkbox" value="${r.id}" ${r.status!=='pending'?'disabled':''}></td><td>#${r.id}</td><td>${esc(r.kind)}</td><td>${esc(r.author_id)}</td><td>${esc(r.subject_name||'—')}</td><td>${badge(r.status)}</td><td>${esc(r.created_at)}</td><td>${esc(r.reviewer_id||'—')}</td></tr>`).join('')||'<tr><td colspan="8" class="empty">Fără activitate</td></tr>';$('#actionRequestsTable').innerHTML=reqs.map(r=>`<tr><td>#${r.id}</td><td>${esc(r.requester_id)}</td><td>${esc(r.action_type)}</td><td>${esc(r.requested_at)}</td><td>${badge(r.status)}</td><td>${r.valid_from?`${esc(r.valid_from)} → ${esc(r.valid_until)}`:'—'}</td><td>${r.status==='pending'?`<button class="btn success small" onclick="reviewActionRequest(${r.id},'accept')">Acceptă</button> <button class="btn danger small" onclick="reviewActionRequest(${r.id},'reject')">Respinge</button>`:'—'}</td></tr>`).join('')||'<tr><td colspan="7" class="empty">Fără cereri</td></tr>'}catch(e){toast(e.message,'err')}} window.loadOperations=loadOperations;
function toggleAllOps(v){$$('.op-check:not(:disabled)').forEach(x=>x.checked=v)} window.toggleAllOps=toggleAllOps;
async function bulkReview(action){const ids=$$('.op-check:checked').map(x=>Number(x.value));if(!ids.length)return toast('Selectează cel puțin o înregistrare','err');const reason=action==='reject'?(prompt('Motiv respingere:')||'Respins din panel'):'';try{await api('/api/operations/bulk-review',{method:'POST',body:{ids,action,reason}});toast('Actualizat');loadOperations()}catch(e){toast(e.message,'err')}} window.bulkReview=bulkReview;
async function reviewActionRequest(id,action){const reason=action==='reject'?(prompt('Motiv:')||'Respins'):'';try{await api(`/api/action-requests/${id}/review`,{method:'POST',body:{action,reason}});loadOperations();toast('Cerere actualizată')}catch(e){toast(e.message,'err')}} window.reviewActionRequest=reviewActionRequest;

async function loadCallsigns(){try{const [ranges,lead]=await Promise.all([api('/api/callsigns'),api('/api/leadership-callsigns')]);
const leadershipRanks=['Coordonator Operațional','Comandant Operațional','Director Adjunct C.C.O.','Director General C.C.O.'];if(lead.some(x=>!x.rank))leadershipRanks.push('NECONFIGURAT / MIGRAT V4');
$('#leadershipCallsigns').innerHTML=leadershipRanks.map(rank=>{const rows=lead.filter(x=>rank==='NECONFIGURAT / MIGRAT V4'?!x.rank:x.rank===rank);const free=rows.filter(x=>!x.assigned_to).length;return `<div class="lead-rank-card"><div class="lead-rank-head"><div><span class="section-kicker">COMMAND POOL</span><h3>${esc(rank)}</h3><small>${rows.length} total · ${free} libere</small></div>${(window.CCO.isOwner||window.CCO.isSuperuser)?`<button class="btn small primary" onclick="openLeadershipCallsignModal(null,'${rank==='NECONFIGURAT / MIGRAT V4'?'':esc(rank)}')">+ Adaugă</button>`:''}</div><div class="lead-slot-list">${rows.length?rows.map(x=>`<div class="lead-slot ${x.assigned_to?'used':'free'}"><div><b>${esc(x.callsign)}</b><small>${x.assigned_to?`${esc(x.first_name||'')} ${esc(x.last_name||'')} · ${esc(x.member_rank||'')}`:'LIBER'}</small></div>${(window.CCO.isOwner||window.CCO.isSuperuser)?`<div class="slot-actions"><button class="icon-btn" onclick='openLeadershipCallsignModal(${JSON.stringify(x.id)},${JSON.stringify(x.rank)},${JSON.stringify(x.callsign)},${JSON.stringify(x.note||"")})'>✎</button>${!x.assigned_to?`<button class="icon-btn danger" onclick="deleteLeadershipCallsign(${x.id},'${esc(x.callsign)}')">×</button>`:''}</div>`:''}</div>`).join(''):'<div class="empty compact">Niciun callsign configurat pentru acest grad.</div>'}</div></div>`}).join('');
$('#callsignRanges').innerHTML=ranges.map(r=>`<div class="range-card"><div class="range-head"><div><span class="section-kicker">${esc(r.rank)}</span><h3>${esc(r.prefix)}-${String(r.start_num).padStart(3,'0')} → ${esc(r.prefix)}-${String(r.end_num).padStart(3,'0')}</h3></div><div class="range-numbers"><b>${r.free}</b><small>libere</small></div></div><div class="slot-grid">${r.slots.map(s=>`<button class="slot ${s.state}" onclick="slotAction('${s.callsign}','${s.state}')"><b>${s.callsign}</b><small>${s.state==='used'?esc((s.data.first_name||'')+' '+(s.data.last_name||'')):s.state}</small></button>`).join('')}</div></div>`).join('')||'<div class="empty">Nu există intervale numerice configurate.</div>'}catch(e){toast(e.message,'err')}} window.loadCallsigns=loadCallsigns;
function openRangeModal(){openModal('rangeModal')} window.openRangeModal=openRangeModal;
async function saveRange(){try{await api('/api/callsigns/range',{method:'POST',body:{rank:$('#rangeRank').value,prefix:$('#rangePrefix').value,start:Number($('#rangeStart').value),stop:Number($('#rangeStop').value)}});closeModal('rangeModal');toast('Interval salvat');loadCallsigns()}catch(e){toast(e.message,'err')}} window.saveRange=saveRange;
function slotAction(cs,state){if(state==='used'){if(confirm(`Eliberezi ${cs}?`))releaseCallsign(cs)}else{const uid=prompt(`Discord ID pentru ${cs}:`);if(uid)assignCallsign(uid,cs)}} window.slotAction=slotAction;
async function assignCallsign(user_id,callsign){try{await api('/api/callsigns/assign',{method:'POST',body:{user_id,callsign}});toast('Callsign atribuit');loadCallsigns()}catch(e){toast(e.message,'err')}}
async function releaseCallsign(callsign){try{await api('/api/callsigns/release',{method:'POST',body:{callsign}});toast('Callsign eliberat');loadCallsigns()}catch(e){toast(e.message,'err')}}
function openLeadershipCallsignModal(id=null,rank='',callsign='',note=''){ $('#leadCallsignId').value=id||'';$('#leadCallsignRank').value=rank||$('#leadCallsignRank').options[0]?.value||'';$('#leadCallsignValue').value=callsign||'';$('#leadCallsignNote').value=note||'';$('#leadCallsignModalTitle').textContent=id?'Editează callsign':'Adaugă callsign';openModal('leadershipCallsignModal')} window.openLeadershipCallsignModal=openLeadershipCallsignModal;
async function saveLeadershipCallsign(){const id=$('#leadCallsignId').value;const body={rank:$('#leadCallsignRank').value,callsign:$('#leadCallsignValue').value.trim(),note:$('#leadCallsignNote').value.trim()};try{await api(id?`/api/leadership-callsigns/${id}/edit`:'/api/leadership-callsigns',{method:'POST',body});closeModal('leadershipCallsignModal');toast(id?'Callsign modificat':'Callsign adăugat');loadCallsigns()}catch(e){toast(e.message,'err')}} window.saveLeadershipCallsign=saveLeadershipCallsign;
function deleteLeadershipCallsign(id,name){criticalConfirm('Ștergere callsign',`Ștergi definitiv callsign-ul ${name}?`,async confirm=>{try{await api(`/api/leadership-callsigns/${id}/delete`,{method:'POST',body:{confirm}});loadCallsigns();toast('Callsign șters')}catch(e){toast(e.message,'err')}})} window.deleteLeadershipCallsign=deleteLeadershipCallsign;

async function loadTickets(){try{const rows=await api('/api/tickets?status='+($('#ticketStatus')?.value||'all'));$('#ticketsTable').innerHTML=rows.map(t=>`<tr><td>#${t.id}</td><td>${esc(t.type)}</td><td>${esc(t.creator_id)}</td><td>${esc(t.claimed_by||'—')}</td><td>${badge(t.status)}</td><td>${esc(t.created_at)}</td><td>${t.status==='closed'?`<a class="btn small ghost" href="/ticket/${t.id}/transcript">TXT</a>`:'—'}</td></tr>`).join('')||'<tr><td colspan="7" class="empty">Fără ticket-uri</td></tr>'}catch(e){toast(e.message,'err')}} window.loadTickets=loadTickets;
async function loadTesters(){try{const rows=await api('/api/testers');$('#testersTable').innerHTML=rows.map(m=>`<tr><td>${esc(m.first_name||'')} ${esc(m.last_name||'')}</td><td>${esc(m.callsign||'—')}</td><td>${esc(m.rank||'—')}</td><td>${m.head_tester?'Șef Tester':'Tester'}</td></tr>`).join('')||'<tr><td colspan="4" class="empty">Fără testeri</td></tr>'}catch(e){toast(e.message,'err')}}

async function loadSanctions(){try{const rows=await api('/api/sanctions');$('#sanctionsTable').innerHTML=rows.map(s=>`<tr><td>#${s.id}</td><td>${esc(s.callsign||'—')} ${esc(s.first_name||'')} ${esc(s.last_name||'')}</td><td><b>${s.requested_type==='AV'&&s.type==='FW'?'AV → ':''}${esc(s.type)} ${s.stage}/${s.total_stages}</b></td><td>${esc(s.reason)}</td><td>${esc(s.author_id)}</td><td>${esc(s.expires_at||'—')}</td><td>${badge(s.status)}</td><td>${s.evidence_url?`<a class="btn small ghost" target="_blank" rel="noopener" href="${esc(s.evidence_url)}">Dovadă</a>`:'—'}</td></tr>`).join('')||'<tr><td colspan="8" class="empty">Fără sancțiuni</td></tr>'}catch(e){toast(e.message,'err')}}
async function loadInactivity(){try{const rows=await api('/api/inactivity');$('#inactivityTable').innerHTML=rows.map(r=>`<tr><td>#${r.id}</td><td>${esc(r.callsign||'—')} ${esc(r.first_name||'')} ${esc(r.last_name||'')}</td><td>${esc(r.rank||'—')}</td><td>${r.duration_days} zile</td><td>${esc(r.reason)}</td><td>${badge(r.status)}</td><td>${r.starts_at?`${esc(r.starts_at)} → ${esc(r.ends_at)}`:'—'}</td><td>${r.status==='pending'?`<button class="btn success small" onclick="reviewInactivity(${r.id},'accept')">Acceptă</button> <button class="btn danger small" onclick="reviewInactivity(${r.id},'reject')">Respinge</button>`:'—'}</td></tr>`).join('')||'<tr><td colspan="8" class="empty">Fără cereri</td></tr>'}catch(e){toast(e.message,'err')}}
async function reviewInactivity(id,action){const reason=action==='reject'?(prompt('Motiv:')||'Respins'):'';try{await api(`/api/inactivity/${id}/review`,{method:'POST',body:{action,reason}});loadInactivity();toast('Cerere actualizată')}catch(e){toast(e.message,'err')}} window.reviewInactivity=reviewInactivity;
async function loadResignations(){try{const rows=await api('/api/resignations');$('#resignationsTable').innerHTML=rows.map(r=>`<tr><td>#${r.id}</td><td>${esc(r.callsign||'—')} ${esc(r.first_name||'')} ${esc(r.last_name||'')}</td><td>${esc(r.rank||'—')}</td><td>${esc(r.reason)}</td><td>${r.accepts_pk?'DA':'NU'}</td><td>${badge(r.status)}</td><td>${r.status==='pending'?`<button class="btn success small" onclick="reviewResignation(${r.id},'accept')">Acceptă</button> <button class="btn danger small" onclick="reviewResignation(${r.id},'reject')">Respinge</button>`:'—'}</td></tr>`).join('')||'<tr><td colspan="7" class="empty">Fără cereri</td></tr>'}catch(e){toast(e.message,'err')}}
async function reviewResignation(id,action){const reason=action==='reject'?(prompt('Motiv:')||'Respins'):'';if(action==='accept'&&!confirm('Acceptarea demisiei va elimina rolurile C.C.O., callsign-ul și va da kick. Continui?'))return;try{await api(`/api/resignations/${id}/review`,{method:'POST',body:{action,reason}});loadResignations();toast('Cerere actualizată')}catch(e){toast(e.message,'err')}} window.reviewResignation=reviewResignation;

const secToggles=['antiraid_enabled','antinuke_enabled','antispam_enabled','antimention_enabled','antilink_enabled','nickname_protection','role_lock_enabled','role_permission_guard','protected_rank_roles','callsign_duplicate_guard','command_permission_guard','command_cooldown_enabled','protected_users_enabled','role_escalation_protection','restore_channels','restore_roles','member_role_restore'];
const secAdvanced=['antiraid_joins','antiraid_window_sec','antispam_messages','antispam_window_sec','antispam_timeout_min','antimention_max','antimention_timeout_min','channel_delete_limit','channel_delete_window_sec','role_delete_limit','role_delete_window_sec','mass_kick_limit','mass_kick_window_sec','mass_ban_limit','mass_ban_window_sec','webhook_create_limit','webhook_window_sec','snapshot_interval_min','min_account_age_days','panel_session_minutes','dangerous_action'];
async function loadSecurity(){try{const d=await api('/api/security');securityState={...d.settings};$('#securityCards').innerHTML=secToggles.map(k=>`<div class="security-card"><div class="security-card-top"><b>${k.replaceAll('_',' ')}</b><div class="switch ${securityState[k]==='1'?'on':''}" onclick="toggleSecurity('${k}',this)"></div></div><small>${securityState[k]==='1'?'Activat':'Dezactivat'}</small></div>`).join('');$('#securityAdvanced').innerHTML=secAdvanced.map(k=>`<label>${k.replaceAll('_',' ')}<input data-sec="${k}" value="${esc(securityState[k]??'')}"></label>`).join('');$('#whitelistList').innerHTML=d.whitelist.map(w=>`<span class="chip">${esc(w.user_id)} · ${esc(w.scope)} <b onclick="whitelistRemove('${w.user_id}','${w.scope}')">×</b></span>`).join('')||'<span class="muted">Whitelist gol</span>';$('#protectedUsersList').innerHTML=(d.protected_users||[]).map(u=>`<span class="chip protected-chip">${esc(u.user_id)}${u.note?' · '+esc(u.note):''} <b onclick="protectedUserRemove('${u.user_id}')">×</b></span>`).join('')||'<span class="muted">Ownerul și Superuserii sunt protejați implicit.</span>'}catch(e){toast(e.message,'err')}}
function toggleSecurity(k,el){securityState[k]=securityState[k]==='1'?'0':'1';el.classList.toggle('on')} window.toggleSecurity=toggleSecurity;
async function saveSecurity(){try{$$('[data-sec]').forEach(i=>securityState[i.dataset.sec]=i.value);await api('/api/security',{method:'POST',body:securityState});toast('Security salvat');loadSecurity()}catch(e){toast(e.message,'err')}} window.saveSecurity=saveSecurity;
async function whitelistAdd(){try{await api('/api/security/whitelist',{method:'POST',body:{action:'add',user_id:$('#wlUser').value,scope:$('#wlScope').value||'all'}});loadSecurity()}catch(e){toast(e.message,'err')}} window.whitelistAdd=whitelistAdd;
async function whitelistRemove(user_id,scope){try{await api('/api/security/whitelist',{method:'POST',body:{action:'remove',user_id,scope}});loadSecurity()}catch(e){toast(e.message,'err')}} window.whitelistRemove=whitelistRemove;
async function protectedUserAdd(){try{await api('/api/security/protected-users',{method:'POST',body:{action:'add',user_id:$('#protectedUserId').value,note:$('#protectedUserNote').value}});$('#protectedUserId').value='';$('#protectedUserNote').value='';loadSecurity();toast('Utilizator protejat')}catch(e){toast(e.message,'err')}} window.protectedUserAdd=protectedUserAdd;
async function protectedUserRemove(user_id){try{await api('/api/security/protected-users',{method:'POST',body:{action:'remove',user_id}});loadSecurity()}catch(e){toast(e.message,'err')}} window.protectedUserRemove=protectedUserRemove;
async function loadBackups(){try{const rows=await api('/api/backups');$('#backupsTable').innerHTML=rows.map(b=>`<tr><td>#${b.id}</td><td>${esc(b.kind)}</td><td>${b.roles}</td><td>${b.channels}</td><td>${esc(b.created_at)}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">Fără backup-uri</td></tr>'}catch(e){toast(e.message,'err')}}
function createBackup(){criticalConfirm('Snapshot server','Creează un snapshot complet al structurii curente?',async confirm=>{try{await api('/api/backups/create',{method:'POST',body:{confirm}});toast('Snapshot creat');loadBackups()}catch(e){toast(e.message,'err')}})} window.createBackup=createBackup;

async function loadLogs(){try{const p=new URLSearchParams({q:$('#logSearch')?.value||'',type:$('#logType')?.value||'all'}),d=await api('/api/logs?'+p);if($('#logType')&&$('#logType').options.length===1)d.types.forEach(t=>$('#logType').insertAdjacentHTML('beforeend',`<option>${esc(t)}</option>`));$('#logsFeed').innerHTML=d.rows.map(x=>`<div class="log-item"><b>${esc(x.type)}</b><small>actor ${esc(x.actor_id||'system')} · target ${esc(x.target_id||'—')} · ${esc(x.details||'')} · ${esc(x.created_at)}</small></div>`).join('')||'<div class="empty">Fără loguri</div>'}catch(e){toast(e.message,'err')}} window.loadLogs=loadLogs;

const roleKeys=['role_cco','role_leadership','role_tester','role_head_tester','role_inactive','role_av_1_1','role_fw_1_3','role_fw_2_3','role_fw_3_3','rank_role_detectiv_stagiar','rank_role_detectiv','rank_role_investigator_operativ','rank_role_investigator_principal','rank_role_ofiter_coordonator_caz','rank_role_sef_serviciu_investigatii','rank_role_coordonator_operational','rank_role_comandant_operational','rank_role_director_adjunct','rank_role_director_general','role_unverified'];
const channelKeys=['welcome_channel','leave_channel','log_roles','log_timesheets','log_tickets','log_security','log_buletine','log_filaje','log_interogatorii','log_actiuni','log_cereri_actiune','log_demisie','log_inactivitate','log_sanctiuni','ticket_category'];let configMeta={},configValues={};
async function loadConfig(){try{const[d,meta]=await Promise.all([api('/api/config'),api('/api/discord-meta')]);configValues=d.config||{};configMeta=meta;$('#configRoles').innerHTML=roleKeys.map(k=>selectField(k,meta.roles,configValues[k])).join('');$('#configChannels').innerHTML=channelKeys.map(k=>selectField(k,k==='ticket_category'?meta.categories:meta.channels,configValues[k])).join('')}catch(e){toast(e.message,'err')}} function selectField(k,items,val){return `<label>${k.replaceAll('_',' ')}<select data-config="${k}"><option value="">— neconfigurat —</option>${items.map(x=>`<option value="${x.id}" ${String(x.id)===String(val)?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label>`} async function saveConfig(){try{const body={};$$('[data-config]').forEach(s=>body[s.dataset.config]=s.value);await api('/api/config',{method:'POST',body});toast('Configurare salvată')}catch(e){toast(e.message,'err')}} window.saveConfig=saveConfig;

async function loadSuperusers(){try{const rows=await api('/api/superusers');$('#superusersGrid').innerHTML=rows.map(u=>`<div class="user-card"><span class="section-kicker">SUPERUSER</span><h3>${esc(u.user_id)}</h3><small class="muted">Adăugat: ${esc(u.added_at)}</small><div class="permission-grid">${Object.entries(u.permissions).map(([k,v])=>`<span class="perm-chip ${v?'on':''}" ${window.CCO.isOwner?`onclick="toggleSuperPerm('${u.user_id}','${k}',${v?'false':'true'})"`:''}>${esc(k)}</span>`).join('')}</div>${window.CCO.isOwner?`<button class="btn danger small" onclick="removeSuperuser('${u.user_id}')">Elimină</button>`:''}</div>`).join('')||'<div class="empty">Fără superuseri</div>'}catch(e){toast(e.message,'err')}} async function addSuperuser(){try{await api('/api/superusers',{method:'POST',body:{action:'add',user_id:$('#superuserId').value}});loadSuperusers()}catch(e){toast(e.message,'err')}} window.addSuperuser=addSuperuser;async function removeSuperuser(id){if(!confirm('Elimini Superuser?'))return;try{await api('/api/superusers',{method:'POST',body:{action:'remove',user_id:id}});loadSuperusers()}catch(e){toast(e.message,'err')}} window.removeSuperuser=removeSuperuser;async function toggleSuperPerm(id,module,allowed){try{await api(`/api/superusers/${id}/permissions`,{method:'POST',body:{[module]:allowed}});loadSuperusers()}catch(e){toast(e.message,'err')}} window.toggleSuperPerm=toggleSuperPerm;

const saved=localStorage.getItem('cco-tab'),available=$(`.nav-item[data-tab="${saved}"]`);switchTab(available?saved:$('.nav-item')?.dataset.tab||'dashboard');
